In [45]:
import numpy as np

import pyswarms as ps
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9, 'k':5, 'p':2}

# Call instance of PSO
optimizer = ps.discrete.BinaryPSO(n_particles=10, dimensions=10, options=options)
itrait=[]
theta=[]
def func(x):
    print(x)
    return x[0]
cost, pos = optimizer.optimize(func, iters=2)

2022-10-31 12:10:33,935 - pyswarms.discrete.binary - INFO - Optimize for 2 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 5, 'p': 2}
pyswarms.discrete.binary: 100%|██████████|2/2, best_cost=0
2022-10-31 12:10:33,944 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.0, best pos: [0 0 1 0 0 0 1 0 0 0]


[[0 0 1 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 1 0 1 0]
 [0 0 1 1 1 0 0 0 1 0]
 [1 0 1 0 0 1 1 0 1 0]
 [1 1 1 1 1 0 0 1 0 1]
 [0 0 0 0 0 1 1 1 1 0]
 [1 1 0 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 1 1 1]
 [0 0 1 1 0 1 1 0 0 0]
 [1 0 1 0 0 1 0 1 0 0]]
[[0 1 0 1 1 0 1 0 1 1]
 [0 1 0 0 1 1 1 1 1 0]
 [0 1 0 1 1 0 1 1 1 1]
 [0 1 0 1 1 0 1 0 1 0]
 [0 1 0 0 1 1 1 1 1 0]
 [0 1 0 1 1 0 1 1 1 0]
 [0 1 0 1 1 1 1 0 0 0]
 [0 1 0 1 1 0 1 1 1 0]
 [0 1 0 1 1 0 1 1 1 0]
 [0 1 0 1 1 0 1 1 1 0]]
